import json
from datetime import datetime
from models import TestSession, TestSessionReading, TestingRequest, TestResult


class TestSessionHTMLService:
    """Renders a single test session as a styled HTML report."""

    def generate_html(
        self,
        session: TestSession,
        readings: list[TestSessionReading],
        request: TestingRequest,
        test_result: TestResult | None = None,
    ) -> str:
        req_num = getattr(request, "request_number", "") or ""
        eq_name = (request.equipment_type.name if request and request.equipment_type else "") or ""
        session_name = session.session_name or f"Session {session.session_number}"
        session_date_str = session.session_date.strftime("%d %b %Y") if session.session_date else "-"
        started_str = session.started_at.strftime("%d/%m/%Y %H:%M") if session.started_at else "-"
        completed_str = session.completed_at.strftime("%d/%m/%Y %H:%M") if session.completed_at else "-"
        env_str = self._fmt(session.environmental_factors) if session.environmental_factors else "-"
        weather_str = session.weather_conditions or "-"

        reading_rows = self._build_reading_rows(readings)
        no_readings = (
            '<tr><td colspan="6" style="padding:20px;text-align:center;color:#888">'
            "No readings recorded for this session</td></tr>"
            if not readings
            else ""
        )
        form_section = self._build_form_section(test_result)

        return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Session Report — {session_name}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; background:#f9f9f9 }}
    .header {{ background:#1b3a6b; color:white; padding:20px 24px; border-radius:10px 10px 0 0 }}
    .header h1 {{ margin:0; font-size:20px }}
    .header p  {{ margin:6px 0 0; font-size:13px; opacity:.8 }}
    .body  {{ background:white; padding:20px 24px; border-radius:0 0 10px 10px; box-shadow:0 2px 8px rgba(0,0,0,.1) }}
    .meta-grid {{ display:grid; grid-template-columns:1fr 1fr; gap:10px; margin-bottom:20px }}
    .meta-item label {{ color:#666; font-size:12px; display:block; margin-bottom:3px }}
    .meta-item span  {{ font-size:14px; font-weight:600 }}
    .section-title {{ font-size:15px; font-weight:700; color:#1b3a6b; border-bottom:2px solid #e8f0fe; padding-bottom:6px; margin:20px 0 12px }}
    table.readings {{ width:100%; border-collapse:collapse; font-size:13px }}
    table.readings th {{ background:#1b3a6b; color:white; padding:8px 10px; text-align:left }}
    table.readings tr:nth-child(even) {{ background:#f5f8ff }}
    .footer {{ margin-top:24px; font-size:11px; color:#aaa; text-align:center }}
  </style>
</head>
<body>
  <div class="header">
    <h1>Session Report — {session_name}</h1>
    <p>Request: {req_num} &nbsp;|&nbsp; Equipment: {eq_name}</p>
  </div>
  <div class="body">
    <div style="margin-bottom:16px">{self._status_badge(session.status or 'scheduled')}</div>

    <div class="meta-grid">
      <div class="meta-item"><label>Session Number</label><span>{session.session_number}</span></div>
      <div class="meta-item"><label>Session Date</label><span>{session_date_str}</span></div>
      <div class="meta-item"><label>Started At</label><span>{started_str}</span></div>
      <div class="meta-item"><label>Completed At</label><span>{completed_str}</span></div>
      <div class="meta-item"><label>Weather Conditions</label><span>{weather_str}</span></div>
      <div class="meta-item"><label>Environmental Factors</label><span>{env_str}</span></div>
      {"<div class='meta-item'><label>Conducted By</label><span>" + self._fmt(session.conducted_by) + "</span></div>" if session.conducted_by else ""}
      {"<div class='meta-item'><label>Witnessed By</label><span>" + self._fmt(session.witnessed_by) + "</span></div>" if session.witnessed_by else ""}
    </div>

    {"<p><b>Notes:</b> " + (session.notes or "") + "</p>" if session.notes else ""}

    {form_section}

    <div class="section-title">Readings ({len(readings)})</div>
    <table class="readings">
      <thead>
        <tr>
          <th>#</th><th>Time</th><th>Measurement Data</th>
          <th>Equipment Serial</th><th>Result</th><th>Remarks</th>
        </tr>
      </thead>
      <tbody>
        {reading_rows}
        {no_readings}
      </tbody>
    </table>

    <div class="footer">
      Generated by SEACMS &nbsp;|&nbsp; KPTCL &nbsp;|&nbsp; {datetime.now().strftime("%d %b %Y %H:%M")}
    </div>
  </div>
</body>
</html>"""

    # ── private helpers ────────────────────────────────────────────────────────

    def _fmt(self, v) -> str:
        if v is None:
            return "-"
        if isinstance(v, list) and v and isinstance(v[0], dict):
            cols = list(v[0].keys())
            header = "".join(
                f"<th style='padding:4px 8px;background:#e8f0fe;color:#1b3a6b;"
                f"font-size:11px;white-space:nowrap'>{c.replace('_',' ').title()}</th>"
                for c in cols
            )
            rows_html = ""
            for row in v:
                cells = "".join(
                    f"<td style='padding:4px 8px;border:1px solid #e0e0e0;font-size:11px'>"
                    f"{row.get(c, '—')}</td>"
                    for c in cols
                )
                rows_html += f"<tr>{cells}</tr>"
            return (
                f"<table style='border-collapse:collapse;width:100%;margin:2px 0'>"
                f"<tr>{header}</tr>{rows_html}</table>"
            )
        if isinstance(v, list):
            return ", ".join(str(i) for i in v) if v else "—"
        if isinstance(v, dict):
            return f"<pre style='margin:0;font-size:12px'>{json.dumps(v, indent=2)}</pre>"
        return str(v)

    def _status_badge(self, s: str) -> str:
        palette = {
            "completed":   ("#1a7340", "#e8f5e9"),
            "in_progress": ("#c75b00", "#fff3e0"),
            "scheduled":   ("#1b3a6b", "#e8f0fe"),
        }
        fg, bg = palette.get(s, ("#555", "#f5f5f5"))
        return (
            f'<span style="background:{bg};color:{fg};padding:3px 10px;'
            f'border-radius:12px;font-size:12px;font-weight:600">'
            f"{s.replace('_',' ').upper()}</span>"
        )

    def _build_reading_rows(self, readings: list) -> str:
        html = ""
        for r in readings:
            rd = r.reading_data or {}
            data_html = "".join(
                f"<div style='margin:2px 0'><b style='color:#1b3a6b'>{k.replace('_',' ').title()}</b>: {self._fmt(v)}</div>"
                for k, v in rd.items()
            ) or "<span style='color:#aaa'>—</span>"
            result_s = (r.result_status or "").lower()
            result_color = "#1a7340" if result_s == "pass" else "#b71c1c" if result_s == "fail" else "#c75b00"
            result_bg   = "#e8f5e9"  if result_s == "pass" else "#ffebee"  if result_s == "fail" else "#fff3e0"
            html += (
                f"<tr>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;text-align:center;font-weight:600'>{r.reading_number}</td>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;white-space:nowrap'>{self._fmt(r.reading_time)}</td>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;font-size:12px'>{data_html}</td>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;text-align:center'>{self._fmt(r.equipment_serial)}</td>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;text-align:center;background:{result_bg};color:{result_color};font-weight:700;border-radius:4px'>{(r.result_status or '—').upper()}</td>"
                f"<td style='padding:6px 10px;border:1px solid #e0e0e0;font-size:12px;color:#555'>{self._fmt(r.remarks)}</td>"
                f"</tr>"
            )
        return html

    def _kit_html(self, test_result) -> str:
        if not (test_result and test_result.testing_kit_id and test_result.testing_kit):
            return ""
        kit = test_result.testing_kit
        np = kit.nameplate_data or {}
        kit_type = (
            np.get("kit_subtype")
            or kit.bay_number
            or (kit.equipment_type.name if kit.equipment_type else "Testing Kit")
        )
        kit_loc = kit.department.name if kit.department else "—"
        td = "padding:6px 10px;border:1px solid #e0e0e0"
        return (
            '<div class="section-title">Testing Kit Used</div>'
            '<table class="readings" style="margin-bottom:8px"><tbody>'
            f"<tr><td style='{td};color:#555;font-size:12px;width:35%'>UEIC</td><td style='{td};font-size:13px'>{kit.ueic or '—'}</td></tr>"
            f"<tr><td style='{td};color:#555;font-size:12px'>Kit Type</td><td style='{td};font-size:13px'>{kit_type}</td></tr>"
            f"<tr><td style='{td};color:#555;font-size:12px'>Manufacturer</td><td style='{td};font-size:13px'>{kit.manufacturer or '—'}</td></tr>"
            f"<tr><td style='{td};color:#555;font-size:12px'>Model Number</td><td style='{td};font-size:13px'>{kit.model_number or '—'}</td></tr>"
            f"<tr><td style='{td};color:#555;font-size:12px'>Serial Number</td><td style='{td};font-size:13px'>{kit.factory_serial_number or '—'}</td></tr>"
            f"<tr><td style='{td};color:#555;font-size:12px'>Location</td><td style='{td};font-size:13px'>{kit_loc}</td></tr>"
            "</tbody></table>"
        )

    def _build_form_section(self, test_result) -> str:
        if not (test_result and test_result.test_data):
            return ""
        td = test_result.test_data
        overall = (td.get("overall_result") or "").upper()
        result_color = "#1a7340" if overall == "PASS" else "#b71c1c" if overall == "FAIL" else "#555"
        result_bg    = "#e8f5e9" if overall == "PASS" else "#ffebee" if overall == "FAIL" else "#f5f5f5"
        rows_html = "".join(
            f"<tr>"
            f"<td style='padding:6px 10px;border:1px solid #e0e0e0;color:#555;font-size:12px'>{k.replace('_',' ').title()}</td>"
            f"<td style='padding:6px 10px;border:1px solid #e0e0e0;font-size:13px'>{self._fmt(v)}</td>"
            f"</tr>"
            for k, v in td.items()
            if k != "overall_result"
        )
        return (
            '<div class="section-title">Form Submission</div>'
            '<table class="readings" style="margin-bottom:8px">'
            '<thead><tr><th style="width:35%">Field</th><th>Value</th></tr></thead>'
            f"<tbody>{rows_html}"
            f"<tr>"
            f"<td style='padding:6px 10px;border:1px solid #e0e0e0;font-weight:700'>Overall Result</td>"
            f"<td style='padding:6px 10px;border:1px solid #e0e0e0;background:{result_bg};color:{result_color};font-weight:700'>{overall or '—'}</td>"
            f"</tr></tbody></table>"
            + self._kit_html(test_result)
        )
