"""
Reporting Suite Endpoints
=========================
GET  /reports/definitions              List all report definitions
POST /reports/definitions              Create ad-hoc definition
GET  /reports/definitions/{id}         Get one definition
PUT  /reports/definitions/{id}         Update definition
DELETE /reports/definitions/{id}       Delete (deactivate) custom definition
GET  /reports/definitions/query-keys   List available query keys

POST /reports/definitions/{id}/run     Generate report -> returns binary file
GET  /reports/logs                     List generation history
GET  /reports/logs/{id}                Get one log entry
"""

from typing import Optional
from uuid import UUID

import os

from fastapi import APIRouter, Depends, Query, HTTPException
from fastapi.responses import Response, FileResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from auth_utils import get_current_user
from database import get_db
from models import User, ReportQueryKey
from services.reporting_service import ReportingService

router = APIRouter(
    prefix="/reports",
    tags=["reports"],
    dependencies=[Depends(get_current_user)],
)


# ── Helpers ────────────────────────────────────────────────────────────────

def _svc(db: Session, current_user: User,
         org_id: Optional[UUID] = None) -> ReportingService:
    """Resolve org from user's OrgUserRole if not supplied."""
    resolved = org_id
    if resolved is None:
        from models import OrgUserRole, OrgRole
        row = (
            db.query(OrgUserRole)
            .filter(OrgUserRole.user_id == current_user.id,
                    OrgUserRole.is_active.is_(True))
            .first()
        )
        if row:
            role = db.query(OrgRole).filter(OrgRole.id == row.org_role_id).first()
            if role:
                resolved = role.organization_id
    return ReportingService(db, org_id=resolved,
                            dept_ids=_user_dept_ids(db, current_user, resolved))


def _report_has_recipients(db: Session, defn, event: str, org_id) -> bool:
    """True when a report-ready notification for `defn` would reach someone:
    the definition's own Recipient Roles, or the event's email template roles
    (org override first, else the global default)."""
    if defn.recipient_roles:
        return True
    from models import NotificationTemplate
    tmpl = (
        db.query(NotificationTemplate)
        .filter(NotificationTemplate.event_type == event,
                NotificationTemplate.channel == "email",
                NotificationTemplate.is_active.is_(True),
                (NotificationTemplate.organization_id == org_id)
                | NotificationTemplate.organization_id.is_(None))
        .order_by(NotificationTemplate.organization_id.desc().nulls_last())
        .first()
    )
    return bool(tmpl and (tmpl.recipient_roles or tmpl.extra_recipient_emails))


def _email_report_to_user(db: Session, user: User, org_id, report_name: str,
                          files: list) -> None:
    """Email a just-generated report straight to `user`, file attached — for
    Run now on a report that has no recipients configured."""
    if not user.email:
        return
    from utils.email_service import EmailService
    from services.integration_settings_service import get_effective_smtp_config
    EmailService(get_effective_smtp_config(db, org_id)).send_multi_attachment_email_starttls_bcc(
        bcc_emails=[user.email],
        subject=f"[CogniWatt] Report Ready — {report_name}",
        body_html=(
            f"<h3 style='color:#1E3C72'>{report_name}</h3>"
            "<p>The report you ran is attached to this email. It is also "
            "available in SEACMS under Reporting Center &rarr; Log.</p>"
            "<p style='color:#888;font-size:12px'>Generated by CogniWatt SEACMS</p>"
        ),
        # files: [(raw, filename, content_type), ...] — both for "Both".
        attachments=[{"content": raw, "filename": fname,
                      "mime_type": (ctype or "application/octet-stream").split(";")[0]}
                     for raw, fname, ctype in files],
    )


def _user_dept_ids(db: Session, current_user: User, org_id) -> Optional[list]:
    """Department subtree a department-scoped user may see in reports, or
    None (no restriction) for org admins / users with no department — same
    scoping rule the dashboards use (utils.common_service)."""
    from utils.common_service import get_dept_subtree_ids, get_user_dept_scope
    is_org_admin, dept_id = get_user_dept_scope(db, current_user.id, org_id)
    if is_org_admin or not dept_id:
        return None
    return list(get_dept_subtree_ids(db, dept_id))


def _defn_to_dict(defn) -> dict:
    return {
        "id":               str(defn.id),
        "name":             defn.name,
        "description":      defn.description,
        "query_key":        defn.query_key,
        "parameters":       defn.parameters,
        "output_format":    defn.output_format,
        "frequency":        defn.frequency,
        "recipient_roles":  defn.recipient_roles,
        "is_active":        defn.is_active,
        "is_system":        defn.is_system,
        "last_generated_at": defn.last_generated_at.isoformat()
                              if defn.last_generated_at else None,
        "cts":              defn.cts.isoformat() if defn.cts else None,
    }


def _log_to_dict(log) -> dict:
    return {
        "id":             str(log.id),
        "definition_id":  str(log.definition_id),
        "output_format":  log.output_format,
        "file_name":      log.file_name,
        "file_size":      log.file_size,
        "row_count":      log.row_count,
        "status":         log.status,
        "error_message":  log.error_message,
        "started_at":     log.started_at.isoformat()   if log.started_at   else None,
        "completed_at":   log.completed_at.isoformat() if log.completed_at else None,
        "cts":            log.cts.isoformat()           if log.cts          else None,
    }


# ── Pydantic schemas ───────────────────────────────────────────────────────

class DefinitionCreate(BaseModel):
    name:            str
    description:     Optional[str] = None
    query_key:       str
    parameters:      dict = {}
    output_format:   str  = "excel"
    frequency:       str  = "on_demand"
    recipient_roles: list = []


class DefinitionUpdate(BaseModel):
    name:            Optional[str]  = None
    description:     Optional[str]  = None
    parameters:      Optional[dict] = None
    output_format:   Optional[str]  = None
    frequency:       Optional[str]  = None
    recipient_roles: Optional[list] = None
    is_active:       Optional[bool] = None


class RunRequest(BaseModel):
    parameters:    dict = {}
    output_format: str  = "excel"   # excel | pdf


class ConsolidatedReportRequest(BaseModel):
    department_id:     UUID
    equipment_type_id: int
    test_type_ids:     list[int] = []
    date_from:         Optional[str] = None   # "YYYY-MM-DD"
    date_to:           Optional[str] = None
    equipment_ids:     Optional[list[UUID]] = None
    delivery:          str = "on_demand"      # on_demand | email
    output_format:     str = "pdf"            # on_demand: pdf | excel  (email always sends both)


# ── Endpoints ──────────────────────────────────────────────────────────────

@router.get("/definitions/query-keys")
def get_query_keys(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return available report query keys from the database."""
    keys = (
        db.query(ReportQueryKey)
        .filter(ReportQueryKey.is_active.is_(True))
        .order_by(ReportQueryKey.group_name, ReportQueryKey.sort_order)
        .all()
    )
    return [
        {
            "key":               k.key,
            "label":             k.label,
            "description":       k.description,
            "group_name":        k.group_name,
            "parameters_schema": k.parameters_schema,
        }
        for k in keys
    ]


@router.get("/definitions")
def list_definitions(
    active_only: bool = Query(True),
    org_id: Optional[UUID] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc   = _svc(db, current_user, org_id)
    defs  = svc.list_definitions(active_only=active_only)
    return [_defn_to_dict(d) for d in defs]


@router.post("/definitions", status_code=201)
def create_definition(
    body: DefinitionCreate,
    org_id: Optional[UUID] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc  = _svc(db, current_user, org_id)
    defn = svc.create_definition(body.dict(), user_id=current_user.id)
    return _defn_to_dict(defn)


@router.get("/definitions/{definition_id}")
def get_definition(
    definition_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc  = _svc(db, current_user)
    defn = svc.get_definition(definition_id)
    if not defn:
        raise HTTPException(404, "Report definition not found")
    return _defn_to_dict(defn)


@router.put("/definitions/{definition_id}")
def update_definition(
    definition_id: UUID,
    body: DefinitionUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc = _svc(db, current_user)
    try:
        defn = svc.update_definition(
            definition_id,
            {k: v for k, v in body.dict().items() if v is not None},
            user_id=current_user.id,
        )
    except ValueError as e:
        raise HTTPException(404, str(e))
    return _defn_to_dict(defn)


@router.delete("/definitions/{definition_id}", status_code=204)
def delete_definition(
    definition_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc = _svc(db, current_user)
    try:
        svc.delete_definition(definition_id, user_id=current_user.id)
    except ValueError:
        raise HTTPException(404, "Report definition not found")
    except PermissionError as e:
        raise HTTPException(403, str(e))
    return Response(status_code=204)


@router.post("/definitions/{definition_id}/run")
def run_report(
    definition_id: UUID,
    body: RunRequest,
    org_id: Optional[UUID] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate report and return the file as binary.
    Content-Disposition header carries the filename.
    """
    svc = _svc(db, current_user, org_id)
    # "both" = one Excel + one PDF from the same run, emailed together in ONE
    # email (two separate runs sent two same-subject emails that mail clients
    # thread together, so only the newer file showed). The response is then
    # JSON listing both files; the app downloads each via /reports/download.
    formats = ["excel", "pdf"] if body.output_format == "both" else [body.output_format]
    generated = []   # (raw, filename, content_type)
    try:
        for fmt in formats:
            generated.append(svc.generate(
                definition_id=definition_id,
                parameters=body.parameters,
                output_format=fmt,
                user_id=current_user.id,
            ))
    except ValueError as e:
        # Only a missing definition is a 404 — anything else (a report that
        # can't be department-scoped, a value the renderer rejects) was
        # surfacing as a misleading "404" too.
        msg = str(e)
        raise HTTPException(404 if "not found" in msg.lower() else 422, msg)
    except RuntimeError as e:
        raise HTTPException(422, str(e))
    raw, filename, content_type = generated[0]
    extra_files = [g[1] for g in generated[1:]]

    # Run now always emails the report, same as a scheduled run:
    #   • definition has recipients (its Recipient Roles, or its event
    #     template's roles) → the same "report ready" notification the
    #     scheduled job fires, file(s) attached;
    #   • no recipients anywhere → emailed straight to whoever clicked Run.
    # A definition with no event of its own (on-demand ones) uses the
    # generic scheduled_report_ready event.
    try:
        from models import ReportDefinition
        from services.reporting_service import fire_report_ready
        defn = db.query(ReportDefinition).filter(ReportDefinition.id == definition_id).first()
        if defn:
            event = defn.notification_event or "scheduled_report_ready"
            if _report_has_recipients(db, defn, event, svc.org_id):
                if svc.dept_ids:
                    # Department-only report → notify only this org + department.
                    from utils.common_service import get_user_dept_scope
                    _, _dept = get_user_dept_scope(db, current_user.id, svc.org_id)
                    fire_report_ready(db, defn, filename, organization_id=svc.org_id,
                                      department_id=_dept, event_type=event,
                                      extra_filenames=extra_files)
                else:
                    fire_report_ready(db, defn, filename, event_type=event,
                                      extra_filenames=extra_files)
            else:
                _email_report_to_user(db, current_user, svc.org_id, defn.name, generated)
    except Exception as notif_exc:
        print(f"[Reports] Notification for definition {definition_id} failed: {notif_exc}")

    if len(generated) > 1:
        return {"files": [{"filename": g[1], "content_type": g[2]} for g in generated]}

    return Response(
        content=raw,
        media_type=content_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-Report-Filename":   filename,
            "X-Row-Count":         str(len(raw)),   # approximate
        },
    )


@router.get("/logs")
def list_logs(
    definition_id: Optional[UUID] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    org_id: Optional[UUID] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    svc  = _svc(db, current_user, org_id)
    logs = svc.list_logs(definition_id=definition_id, limit=limit)
    return [_log_to_dict(lg) for lg in logs]


# ── Reporting Center endpoints ─────────────────────────────────────────────────

@router.get("/groups")
def get_report_groups(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Return distinct group_name values for Reporting Center filter chips."""
    from sqlalchemy import distinct
    from models import ReportDefinition
    rows = db.query(distinct(ReportDefinition.group_name)).filter(
        ReportDefinition.group_name.isnot(None)
    ).all()
    return sorted([r[0] for r in rows if r[0]])


@router.get("/download/{filename:path}")
def download_report_file(
    filename: str,
    current_user: User = Depends(get_current_user),
):
    """Serve a previously generated scheduled report file."""
    # Sanitise: strip any path traversal
    safe_name = os.path.basename(filename)
    reports_dir = os.path.join(os.path.dirname(__file__), "..", "uploads", "reports")
    path = os.path.join(reports_dir, safe_name)
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="Report file not found or expired")
    if filename.endswith(".xlsx"):
        media = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    else:
        media = "application/pdf"
    return FileResponse(
        path,
        media_type=media,
        headers={"Content-Disposition": f'attachment; filename="{safe_name}"'},
    )


# ── Consolidated Test Report (multi-equipment, multi-test PDF) ──────────────────

@router.post("/consolidated-test-report")
def consolidated_test_report(
    body: ConsolidatedReportRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Generate a single combined PDF spanning every equipment of the chosen type
    within the user's department subtree, including the selected test types
    completed in the given date range. Grouped per equipment.
    """
    from datetime import date as _date
    from services.consolidated_report_service import ConsolidatedReportService

    def _parse(d: Optional[str]) -> Optional[_date]:
        if not d:
            return None
        try:
            return _date.fromisoformat(d[:10])
        except Exception:
            return None

    # A department-scoped user may only report on their own department
    # subtree — the requested department_id is caller-supplied.
    _allowed = _user_dept_ids(db, current_user, current_user.organization_id)
    if _allowed is not None and str(body.department_id) not in {str(d) for d in _allowed}:
        raise HTTPException(403, "You can only generate reports for your own department.")

    svc = ConsolidatedReportService(db)
    _df, _dt = _parse(body.date_from), _parse(body.date_to)
    _args = dict(
        department_id=body.department_id,
        equipment_type_id=body.equipment_type_id,
        test_type_ids=body.test_type_ids,
        date_from=_df,
        date_to=_dt,
        equipment_ids=body.equipment_ids,
    )
    _stamp = f"{(body.date_from or 'all')}_{(body.date_to or 'all')}"

    # ── EMAIL delivery: send PDF + Excel to the requesting user ────────────────
    if body.delivery == "email":
        if not current_user.email:
            raise HTTPException(400, "Your account has no email address on file.")
        pdf_bytes = svc.generate(**_args)
        xls_bytes = svc.generate_excel(**_args)
        from utils.email_service import EmailService
        from services.integration_settings_service import get_effective_smtp_config
        try:
            # Same org-effective SMTP config (Integration Settings, then .env)
            # the notification emails use — not the bare .env credentials.
            EmailService(get_effective_smtp_config(db, current_user.organization_id)).send_multi_attachment_email_starttls_bcc(
                bcc_emails=[current_user.email],
                subject=f"[Consolidated Test Report] {_stamp}",
                body_html=(
                    "<h3 style='color:#1565C0'>Consolidated Test Report</h3>"
                    "<p>Your requested consolidated test report is attached "
                    "in <strong>PDF</strong> and <strong>Excel</strong> formats.</p>"
                    "<p style='color:#888;font-size:12px'>Generated by CogniWatt SEACMS</p>"
                ),
                attachments=[
                    {"content": pdf_bytes, "filename": f"consolidated_report_{_stamp}.pdf",
                     "mime_type": "application/pdf"},
                    {"content": xls_bytes, "filename": f"consolidated_report_{_stamp}.xlsx",
                     "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                ],
            )
        except Exception as e:
            raise HTTPException(502, f"Failed to send email: {e}")
        return {"status": "sent", "message": f"Report emailed to {current_user.email}"}

    # ── ON-DEMAND delivery: return the file directly ───────────────────────────
    if body.output_format == "excel":
        raw = svc.generate_excel(**_args)
        filename = f"consolidated_report_{_stamp}.xlsx"
        media = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    else:
        raw = svc.generate(**_args)
        filename = f"consolidated_report_{_stamp}.pdf"
        media = "application/pdf"

    return Response(
        content=raw,
        media_type=media,
        headers={
            "Content-Disposition": f'inline; filename="{filename}"',
            "X-Report-Filename": filename,
        },
    )
